feat: add support to filtering by workspaces
npm/libnpmfund pull request #4
Opened 2021-05-12 22:18 UTC by ruyadorno

Adds support to a new `workspaces` option, that accepts an array of
strings, allowing users to filter the resulting fund info to a specific
set of workspaces and their dependencies.

## References
Relates to: https://github.com/npm/statusboard/issues/301

2021-05-12 22:33 UTC, wraithgar commented on index.js
> +const filterWorkspaces = (tree, opts) => {
Is this something arborist should be doing?

2021-05-12 23:05 UTC, isaacs requested changes
Mutating the tree is probably going to have some unfortunate effects.  Better to get a list of what you care about, and only walk those portions of it.  (This is also a fair bit cheaper, since it doesn't have to update edges or walk _all_ the nodes.)

Also, the argument should be _strictly_ workspace names.  Allowing it to be either names or paths opens the door for ambiguity.  (Consider a workspace named `foo` at the path `./bar`, and a workspace named `bar` at the path `./foo`.  What does `workspaces:['foo']` mean?)  We use names everywhere else, since the CLI has that handy, and you have the tree anyway.

Definitely should not land this before you can get Arborist to just hand you a set of nodes that are relied on by some list of workspace names.

2021-05-12 23:05 UTC, isaacs commented on test.js
> +      await read({ path, workspaces: ['a'] }),
It should take the same shaped argument that Arborist does, I think.  Always a list of workspace names, not absolute or relative paths.

2021-05-12 23:05 UTC, isaacs commented on index.js
> +const filterWorkspaces = (tree, opts) => {
Arborist is going to give CLI some very troubled looks when it sees that you've been pruning this tree yourself :joy:

It's probably fine to mutate the tree, but it means we can never use that tree again for anything else.  If `fund` is ever a part of the install flow, or something else, we're kind of in trouble.

2021-05-12 23:05 UTC, isaacs commented on index.js
> +  if (opts && opts.workspaces && opts.workspaces.length) {
The way that Arborist will expose this will be to provide a way to get a `Set` of all nodes that are depended on by a given set of workspace names.

So you'd do something like `const filterSet = Arborist.getWorkspaceSet(tree, ['a', 'b'])`.  The implementation of the function is something like:

```js
// get the actual nodes corresponding to a workspaces list
const getWorkspaceNodes = (tree, workspaces) => {
  const wsMap = tree.workspaces
  if (!wsMap) {
    log.warn('workspaces', 'filter set, but no workspaces present')
    return []
  }

  const nodes = []
  for (const name of workspaces) {
    const path = wsMap.get(name)
    if (!path) {
      log.warn('workspaces', `${name} in filter set, but not in workspaces`)
      continue
    }

    const loc = relpath(tree.realpath, path)
    const node = tree.inventory.get(loc)

    /* istanbul ignore if - should be impossible */
    if (!node) {
      log.warn('workspaces', `${name} in filter set, but no workspace folder present`)
      continue
    }

    nodes.push(node)
  }

  return nodes
}

const filterSet = new Set(getWorkspaceNodes(tree, workspaces))
for (const node of filterSet) {
  for (const edge of node.edgesOut.values()) {
    const target = edge.to.target || edge.to
    if (target)
      filterSet.add(target)
  }
}
// now filterSet contains the nodes we care about
```

2021-05-12 23:05 UTC, isaacs commented on index.js
> +  if (opts && opts.workspaces && opts.workspaces.length) {
Then add something like:

```js
// down in getFundingDependencies
      if (filterSet.size && !filterSet.has(node))
        return empty()
```

2021-05-13 16:09 UTC, isaacs approved these changes
LGTM! :shipit:

2021-05-13 16:11 UTC, closed without merging